### ISSUE TITLE
Source1 Protobuf Update

### ISSUE THREAD

**Issue by ykim** [skadistats/clarity-protobuf#1]
Getting these warnings using clarity,

```
13:25:26.735 [main] WARN  s.c.p.reader.InputSourceProcessor - unknown usermessage of kind 140
```

It looks like it's related to dota_usermessages.proto not being updated. Is it possible to get this updated for clarity 2.1?

**Comment by spheenik** [comment]
Yes. Will update.

Am 21.08.2015 um 22:29 schrieb Young Kim:

**Comment by spheenik** [comment]
This should be fixed by now, I guess :D
