### ISSUE TITLE
Bounty Rune Proto?

### ISSUE THREAD

**Issue by copperstick6** [skadistats/clarity-protobuf#11]
Not seeing any info in the proto re: bounty runes/invis runes/dd/etc. Any idea where to find those protos? I tried ChatMessage

**Comment by spheenik** [comment]
@noxville: Runes should be in entity inventories or entities themselves, right?

**Comment by copperstick6** [comment]
Found it - it's DOTA_CHAT_MESSAGE CHAT_MESSAGE_RUNE_PICKUP, value
5 = bounty
8 = wisdom rune

It would be nice to have these as enums, but I can manage for now

**Comment by Noxville** [comment]
Many of the enums are not exposed in the protos -- which is good because you can still parse replays with slightly older protos without errors or warnings - but bad because you need to still manage these enums yourself if you need to map it.

Even something like Radiant's default team ID being 2, and Dire's being 3 isn't nicely exposed in the message schema.

```
public enum ERuneType {
    DOUBLEDAMAGE(0, "modifier_rune_doubledamage"),
    HASTE(1, "modifier_rune_haste"),
    ILLUSION(2, "modifier_rune_illusion"),
    INVISIBILITY(3, "modifier_rune_invis"),
    REGENERATION(4, "modifier_rune_regen"),
    BOUNTY(5, "modifier_rune_bounty"),
    ARCANE(6, "modifier_rune_arcane"),
    WATER(7, "modifier_rune_water");

    public final int v;
    public final String strValue;

    ERuneType(int v, String str) {
        this.v = v;
        this.strValue = str;
    }
}
```

**Comment by spheenik** [comment]
Thanks, Ben!

**Comment by copperstick6** [comment]
Right - proto is (supposed to be) by default designed to be backwards compatible. It's just awful to try to figure it out for the first time.  
Thanks anyways

**Comment by Noxville** [comment]
Most of the time those values are stored in the game files - for example the item schema, or hero information, or ability information; but yeah agreed it's a pain to work it out for the first time. 

I would imagine that they also have other stuff that they test (on a private test for example) with that they don't necessarily want to risk publishing to the protos; for example a new rune type, or a new hero.
