### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by KenBeanNet** [skadistats/clarity-protobuf#2]
https://github.com/skadistats/clarity-protobuf/blob/master/src/main/proto/common/dota_usermessages.proto

```
CHAT_MESSAGE_RIVER_PAINTED = 99;
CHAT_MESSAGE_SCAN_USED = 100;
```

enum DOTA_CHAT_MESSAGE {}

**Comment by spheenik** [comment]
Fixed in [today's commit](https://github.com/skadistats/clarity-protobuf/commit/06d6a30af89e72b27303afd59faf06092ebfb141)
