### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by STRATZ-Ken** [skadistats/clarity-protobuf#3]
Can we get a new update of Protos, 7.03 was just released and it removed some chat wheel events.

Thanks as always!

**Comment by spheenik** [comment]
All right, I did the update.
They removed the Enum which describes the chat wheel events, which seems to indicate they want to be lazy and only map those in the real client in the future. I removed the binding to the enum but left it there.

So this update might break code that relies on the Enum being bound to the message.
