### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by STRATZ-Ken** [skadistats/clarity-protobuf#4]
Is it possible to get a short 3-4 step guide on how to manually update the protos?

Thanks,

**Comment by spheenik** [comment]
- Pull the upstream repo
- git diff to find out what changed (commit id of my protobufs is in commit message)
- work the diff in
- call the protobuf parser on the changed protobufs (there's .sh and .bat scripts already there)
- build using maven

Are you missing something from the protobufs?

**Comment by spheenik** [comment]
Difficult to explain. I'd rather do it myself ;-)

**Comment by dellis23** [comment]
I don't mind doing it myself and copying previous commits, but I can't find the actual scripts / commands needed for compiling the protobufs to java files once the protobuf changes have been made.

**Comment by dellis23** [comment]
Leaving some breadcrumbs in case anyone else runs into this:

The make file is here: https://github.com/skadistats/clarity-protobuf/blob/master/src/main/proto/make.sh

I had to make a windows version for git bash.  Actually chatgpt wrote it, so blame it for the emojis:

```
#!/bin/bash

# Function to query JSON using jq
query() {
  local __result=$1
  local __query=$2
  local __output=$(./jq.exe -r "$__query" build.json)
  eval $__result="'$__output'"
}

# Set Windows-compatible paths
PROTOC_PATH="./protoc.exe"   # Update this path
OUTPUT_DIR="../java"
INCLUDE_DIR="/xxx/protoc-25.6-win64/include"  # Update this path

# Debug: Print full JSON structure for verification
echo "🔍 Processing build.json content:"
cat build.json | ./jq .

# Get the length of the JSON array
query LEN ". | length"
echo "📌 Found $LEN entries in build.json"

for e in $(seq 0 $(($LEN - 1))); do
  echo "--------------------------------------"
  echo "🔹 Processing entry [$e]"

  query INCLEN ".[$e].include | length"
  echo "📌 Includes count: $INCLEN"

  # Initialize command with protoc path and include paths
  CMD="\"$PROTOC_PATH\" --java_out=\"$OUTPUT_DIR\" --proto_path=\"$INCLUDE_DIR\""

  for i in $(seq 0 $(($INCLEN - 1))); do
    query INCP ".[$e].include[$i]"
    echo "📂 Adding include path: $INCP"
    CMD="$CMD --proto_path=\"$INCP\""
  done

  query P ".[$e].path"
  echo "📂 Base proto path: $P"
  CMD="$CMD --proto_path=\"$P\""

  query B ".[$e].build"
  echo "📝 Proto file to compile: $B"
  CMD="$CMD \"$P/$B\""

  # Debug: Show the full command before executing
  echo "🚀 Executing command: $CMD"
  eval $CMD

done

echo "✅ Proto compilation process complete."
```

You'll need jq.exe and protoc.exe and the proto includes. (https://stedolan.github.io/jq/download/ & https://github.com/protocolbuffers/protobuf/releases).

I got the updated protos from here: https://github.com/SteamDatabase/Protobufs  Had to work around include issues and ended up just removing some things I knew I wouldn't need.

Working on getting changes into EmbeddedPackets.java, which seems like it needs to be done manually?

**Comment by dellis23** [comment]
Looks like a version of protoc older than 3 is needed.  Trying to get 2.6.1, but not seeing the necessary include files in the zips provided: https://github.com/protocolbuffers/protobuf/releases/tag/v2.6.1

**Comment by dellis23** [comment]
Looks like it's just `protobuf-2.6.1/src` in this zip.  After a bit more fiddling, compilation has worked.  Now gonna see if I run into any issues actually parsing deadlock replays using the new information!

**Comment by dellis23** [comment]
Everything _seems_ to be working, but almost all of the new messages I added aren't showing (see https://github.com/skadistats/clarity-protobuf/commit/64b88862fad0af3159b93a02bc9efb799735b1df).  The only one I'm seeing when I use the `dump` command from `clarity-examples` is `AbilitiesChanged`.  Not sure if that command needs modification or these other values just aren't being used or what.
