### ISSUE TITLE
Question: Sell an item

### ISSUE THREAD

**Issue by armoucar** [skadistats/clarity-protobuf#6]
Hi,

I found out that I can use the type `DOTA_COMBATLOG_TYPES.DOTA_COMBATLOG_PURCHASE` to check purchased items when reading a replay.

How about sold items? I can't find a compatible type to identify this action.

Thanks

**Comment by spheenik** [comment]
If there is none in combat log, you'll have to watch the inventory slots in the player entities for stuff that gets removed, and correlate that with a sudden increase in money someone got.

**Comment by armoucar** [comment]
thanks @spheenik, I'm getting used to clarity's API, so I will find ways of getting what I want without this event.

the `clarity-examples` project is very helpful. The lib is really well designed as well. Thanks!

**Comment by spheenik** [comment]
Thank you for the kind words, and have fun using clarity. If you need help, just open a new issue (preferrably on the main clarity project).
