### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by builder-247** [skadistats/clarity-protobuf#8]
Hey, can you update the protos - the new Dota 2 chat uses a `CDOTAUserMsg_ChatMessage` that hasn't been added yet.

**Comment by Markxy** [comment]
Created a fork which handles the new ChatMessage protos.
https://github.com/Markxy/clarity-protobuf

Message handling in the parser is now done like this:
```java
@OnMessage(DotaUserMessages.CDOTAUserMsg_ChatMessage.class)
public void onAllChatMessage(Context ctx, DotaUserMessages.CDOTAUserMsg_ChatMessage message) {
    Integer playerSlot = message.getSourcePlayerId();
    Integer channelType = message.getChannelType();
    String msgText = message.getMessageText();
}
```

Packaged it up into a .jar for a replacement lib until the main repo gets updated:
[clarity-protobuf-4.27-SNAPSHOT.jar.zip](https://github.com/skadistats/clarity-protobuf/files/6264647/clarity-protobuf-4.27-SNAPSHOT.jar.zip)

For cross-reference: https://github.com/odota/web/issues/2747

**Comment by spheenik** [comment]
Sorry for being to slow.
Version 4.27 released just now, which contains the message.
